import { type Book } from "@/types/Books";

export const BOOKS: Book[] = [
	{
		id: "1",
		name: "Cien Años de Soledad",
		publicationDate: new Date(1967, 5, 30),
		pageCount: 417,
		genre: "Novela",
		authorId: "gabriel-garcia-marquez",
		synopsis: "La historia de la familia Buendía en el pueblo ficticio de Macondo.",
		language: "Español",
		publisher: "Editorial Sudamericana",
		isbn: "978-0307474728",
		coverImageUrl: "https://www.crisol.com.pe/media/catalog/product/cache/cf84e6047db2ba7f2d5c381080c69ffe/w/h/whatsapp_image_2023-07-18_at_11.00.40_1_.jpeg",
		description: "El libro se compone de 20 capítulos no titulados, en los cuales se narra una historia con una estructura cíclica temporal, ya que los acontecimientos del pueblo y de la familia Buendía, así como los nombres de los personajes se repiten una y otra vez, fusionando la fantasía con la realidad.",
		awards: [
			{
				title: "Premio Nobel de Literatura",
				year: 1982,
			},
		],
		reviews: [
			{
				reviewer: "John Doe",
				rating: 5,
				comment: "Un clásico de la literatura latinoamericana.",
			},
		],
	},
	{
		id: "2",
		name: "Don Quijote de la Mancha",
		publicationDate: new Date(1605, 1, 16),
		pageCount: 863,
		genre: "Novela",
		authorId: "miguel-de-cervantes",
		synopsis: "Las aventuras del ingenioso hidalgo Don Quijote y su fiel escudero Sancho Panza.",
		language: "Español",
		publisher: "Francisco de Robles",
		isbn: "978-0060934347",
		coverImageUrl: "https://www.crisol.com.pe/media/catalog/product/cache/cf84e6047db2ba7f2d5c381080c69ffe/9/7/9788416540181_ni3sl388vsoqajd0.jpg",
		description: "El libro relata las aventuras y desventuras de un hidalgo de 50 años llamado Alonso Quijano, quien decide ser un caballero andante como aquellos que aparecen en sus libros de caballerías favoritos.",
		awards: [],
		reviews: [
			{
				reviewer: "Jane Smith",
				rating: 5,
				comment: "Una obra maestra de la literatura universal.",
			},
		],
	},
	{
		id: "3",
		name: "1984",
		publicationDate: new Date(1949, 6, 8),
		pageCount: 328,
		genre: "Distopía",
		authorId: "george-orwell",
		synopsis: "Una visión sombría del futuro en un estado totalitario.",
		language: "Inglés",
		publisher: "Secker & Warburg",
		isbn: "978-0451524935",
		coverImageUrl: "https://www.crisol.com.pe/media/catalog/product/cache/cf84e6047db2ba7f2d5c381080c69ffe/9/7/9786124262135.jpg",
		description: "1984 es la antiutopía o distopía más célebre de todas cuantas fueron escritas durante la primera mitad del siglo XX. En ella, Orwell presenta un futuro en el que una dictadura totalitaria interfiere hasta tal punto en la vida privada de los ciudadanos que resulta imposible escapar a su control.",
		awards: [],
		reviews: [
			{
				reviewer: "Alice Johnson",
				rating: 4.5,
				comment: "Profundamente inquietante y relevante.",
			},
		],
	},
	{
		id: "4",
		name: "El Gran Gatsby",
		publicationDate: new Date(1925, 4, 10),
		pageCount: 180,
		genre: "Novela",
		authorId: "f-scott-fitzgerald",
		synopsis: "La historia de Jay Gatsby y su búsqueda del sueño americano.",
		language: "Inglés",
		publisher: "Charles Scribner's Sons",
		isbn: "978-0743273565",
		coverImageUrl: "https://www.crisol.com.pe/media/catalog/product/cache/cf84e6047db2ba7f2d5c381080c69ffe/9/7/9788411407403_yrl9ggifx5bqlq3s.jpg",
		description: "El gran Gatsby a través de los ojos del narrador, Nick Carraway, retrata aquella alocada década de los años veinte, marcada por la ley seca, el jazz y las grandes fiestas que afloraban sobre un mundo de negocios poco lícitos, corrupciones y sueños inalcanzables.",
		awards: [],
		reviews: [
			{
				reviewer: "Bob Brown",
				rating: 5,
				comment: "Una obra trágica y fascinante sobre la ambición y el amor.",
			},
		],
	},
	{
		id: "5",
		name: "Matar a un ruiseñor",
		publicationDate: new Date(1960, 7, 11),
		pageCount: 281,
		genre: "Novela",
		authorId: "harper-lee",
		synopsis: "La lucha contra la injusticia racial en el sur de los Estados Unidos.",
		language: "Inglés",
		publisher: "J.B. Lippincott & Co.",
		isbn: "978-0061120084",
		coverImageUrl: "https://www.crisol.com.pe/media/catalog/product/cache/cf84e6047db2ba7f2d5c381080c69ffe/9/7/9788417216948_f4vstmh5fovgftic.jpg",
		description: "Matar a un ruiseñor muestra una comunidad, la del sur de Estados Unidos durante la década de 1930, dominada por los prejuicios raciales, la desconfianza hacia lo diferente, la rigidez de los vínculos familiares y vecinales, así como por un sistema judicial sin apenas garantías para la población.",
		awards: [
			{
				title: "Premio Pulitzer de Ficción",
				year: 1961,
			},
		],
		reviews: [
			{
				reviewer: "Cathy Green",
				rating: 5,
				comment: "Una novela poderosa sobre la moralidad y la empatía.",
			},
		],
	},
	{
		id: "6",
		name: "El guardián entre el centeno",
		publicationDate: new Date(1951, 7, 16),
		pageCount: 277,
		genre: "Novela",
		authorId: "j-d-salinger",
		synopsis: "La historia de Holden Caulfield, un adolescente que enfrenta la transición a la adultez en Nueva York.",
		language: "Inglés",
		publisher: "Little, Brown and Company",
		isbn: "978-0316769488",
		coverImageUrl: "https://imagessl9.casadellibro.com/a/l/s7/09/9788420674209.webp",
		description: "",
		awards: [],
		reviews: []
	},
	{
		id: "7",
		name: "El corazón es un cazador solitario",
		publicationDate: new Date(1940, 5, 1),
		pageCount: 356,
		genre: "Novela",
		authorId: "carson-mccullers",
		synopsis: "La vida de varios personajes en una pequeña ciudad del sur de Estados Unidos, explorando temas de soledad y aislamiento.",
		language: "Inglés",
		publisher: "Houghton Mifflin",
		isbn: "978-0618526413",
		coverImageUrl: "https://www.crisol.com.pe/media/catalog/product/cache/cf84e6047db2ba7f2d5c381080c69ffe/9/7/9788432232558_m54ehhkhnvb9eklj.jpg",
		description: "",
		awards: [],
		reviews: []
	},
	{
		id: "8",
		name: "Cuestión de justicia",
		publicationDate: new Date(2014, 10, 21),
		pageCount: 368,
		genre: "No ficción",
		authorId: "bryan-stevenson",
		synopsis: "La historia de la lucha de Bryan Stevenson por la justicia y la redención en el sistema judicial estadounidense.",
		language: "Inglés",
		publisher: "Spiegel & Grau",
		isbn: "978-0812984965",
		coverImageUrl: "https://imagessl5.casadellibro.com/a/l/s7/55/9788499426655.webp",
		description: "",
		awards: [],
		reviews: []
	},
	{
		id: "9",
		name: "La carretera",
		publicationDate: new Date(2006, 9, 26),
		pageCount: 287,
		genre: "Novela",
		authorId: "cormac-mccarthy",
		synopsis: "Un padre y su hijo viajan por un paisaje post-apocalíptico, enfrentando peligros y buscando esperanza.",
		language: "Inglés",
		publisher: "Alfred A. Knopf",
		isbn: "978-0307387899",
		coverImageUrl: "https://www.crisol.com.pe/media/catalog/product/cache/cf84e6047db2ba7f2d5c381080c69ffe/9/7/9788439741008_6dqdufi9lornxuly.jpg",
		description: "",
		awards: [],
		reviews: []
	},
	{
		id: "10",
		name: "El color púrpura",
		publicationDate: new Date(1982, 10, 1),
		pageCount: 295,
		genre: "Novela",
		authorId: "alice-walker",
		synopsis: "La historia de Celie, una mujer afroamericana en el sur de Estados Unidos, y su lucha por encontrar su identidad y libertad.",
		language: "Inglés",
		publisher: "Harcourt Brace Jovanovich",
		isbn: "978-0156028356",
		coverImageUrl: "https://www.crisol.com.pe/media/catalog/product/cache/cf84e6047db2ba7f2d5c381080c69ffe/9/7/9788466374569_20cykrlnrrjmjezt.jpg",
		description: "",
		awards: [],
		reviews: []
	},
	{
		id: "11",
		name: "Rayuela",
		publicationDate: new Date(1963, 6, 28),
		pageCount: 736,
		genre: "Antinovela",
		authorId: "julio-cortazar",
		synopsis: "La historia de Horacio Oliveira y su relación con 'la Maga', explorando la subjetividad del lector con múltiples finales.",
		language: "Español",
		publisher: "Editorial Sudamericana",
		isbn: "978-9500431514",
		coverImageUrl: "https://www.crisol.com.pe/media/catalog/product/cache/cf84e6047db2ba7f2d5c381080c69ffe/9/7/9786124346491_fnuyk3tvtygeu1l4.jpg",
		description: "",
		awards: [],
		reviews: []
	},
	{
		id: "12",
		name: "El extranjero",
		publicationDate: new Date(1942, 1, 1),
		pageCount: 123,
		genre: "Novela",
		authorId: "albert-camus",
		synopsis: "La historia de Meursault, un hombre indiferente que comete un asesinato y enfrenta las consecuencias de sus actos.",
		language: "Francés",
		publisher: "Gallimard",
		isbn: "978-2070360024",
		coverImageUrl: "https://www.crisol.com.pe/media/catalog/product/cache/cf84e6047db2ba7f2d5c381080c69ffe/9/7/9789500427777_omqqa0pnpl6bwhuy.jpg",
		description: "",
		awards: [],
		reviews: []
	},
	{
		id: "13",
		name: "La peste",
		publicationDate: new Date(1947, 6, 10),
		pageCount: 308,
		genre: "Novela",
		authorId: "albert-camus",
		synopsis: "La crónica de una epidemia de peste en la ciudad argelina de Orán y la respuesta de sus habitantes.",
		language: "Francés",
		publisher: "Gallimard",
		isbn: "978-2070360420",
		coverImageUrl: "https://www.crisol.com.pe/media/catalog/product/cache/cf84e6047db2ba7f2d5c381080c69ffe/9/7/9789877692334_z3qoc3lwbex4rdld.jpg",
		description: "",
		awards: [],
		reviews: []
	},
	{
		id: "14",
		name: "El mito de Sísifo",
		publicationDate: new Date(1942, 10, 1),
		pageCount: 194,
		genre: "Ensayo",
		authorId: "albert-camus",
		synopsis: "Un ensayo filosófico que explora el absurdo de la vida y cómo los seres humanos pueden encontrar sentido en un mundo sin sentido.",
		language: "Francés",
		publisher: "Gallimard",
		isbn: "978-2070325023",
		coverImageUrl: "https://www.crisol.com.pe/media/catalog/product/cache/cf84e6047db2ba7f2d5c381080c69ffe/e/l/el-mite-de-sisif_qwhj7h1icoqd78kc.jpg",
		description: "",
		awards: [],
		reviews: []
	},
	{
		id: "15",
		name: "La caída",
		publicationDate: new Date(1956, 9, 1),
		pageCount: 147,
		genre: "Novela",
		authorId: "albert-camus",
		synopsis: "La confesión de un abogado parisino que revela su caída moral y su lucha con la culpa y la redención.",
		language: "Francés",
		publisher: "Gallimard",
		isbn: "978-2070360079",
		coverImageUrl: "https://imagessl8.casadellibro.com/a/l/s7/48/9789500397148.webp",
		description: "",
		awards: [],
		reviews: []
	},
	{
		id: "16",
		name: "Orgullo y prejuicio",
		publicationDate: new Date(1813, 1, 28),
		pageCount: 432,
		genre: "Novela",
		authorId: "jane-austen",
		synopsis: "La historia de Elizabeth Bennet y su relación con el orgulloso Sr. Darcy, explorando temas de amor, clase social y prejuicio.",
		language: "Inglés",
		publisher: "T. Egerton, Whitehall",
		isbn: "978-1503290563",
		coverImageUrl: "https://www.crisol.com.pe/media/catalog/product/cache/cf84e6047db2ba7f2d5c381080c69ffe/9/7/9788497944625_y8hmgedvitfbspj8.jpg",
		description: "",
		awards: [],
		reviews: []
	},
	{
		id: "17",
		name: "Crimen y castigo",
		publicationDate: new Date(1866, 1, 1),
		pageCount: 671,
		genre: "Novela",
		authorId: "fyodor-dostoevsky",
		synopsis: "La historia de Raskolnikov, un joven estudiante que comete un asesinato y enfrenta las consecuencias morales y psicológicas de su crimen.",
		language: "Ruso",
		publisher: "The Russian Messenger",
		isbn: "978-0140449136",
		coverImageUrl: "https://www.crisol.com.pe/media/catalog/product/cache/cf84e6047db2ba7f2d5c381080c69ffe/9/7/9788491050063_o1hxqvvubhedim2l.jpg",
		description: "",
		awards: [],
		reviews: []
	},
	
	
	
];